@startuml segment lifecycle
hide empty description
[*] --> TokenSelected
state TokenSelected {

}
TokenSelected --> SourcePatternSelected: 自動
TokenSelected: 這裡處理 source pattern
TokenSelected: 的查詢和自動標示
SourcePatternSelected --> TargetPatternSelected
SourcePatternSelected: 這個時候 target pattern 沒有選
TargetPatternSelected: 這個時候還可以選其他
TargetPatternSelected: 的 target pattern
TokenSelected --> [*] : TokenUnselect
TargetPatternSelected --> SourcePatternSelected
TargetPatternSelected --> TargetPatternConfirmed : AcceptInitialTranslation
TargetPatternConfirmed --> TargetPatternSelected
TargetPatternConfirmed: Lock target pattern
TargetPatternConfirmed: , including dropdown & pieces
TargetPatternConfirmed: 這個時候可以開始編輯譯文
TargetPatternSelected --> [*] : TokenUnselect
@enduml
